import {
  DEFAULT_CHARACTER_TAB,
  DEFAULT_FOCUSED_GOALS_ENABLED,
  DEFAULT_SCREEN_ID,
  DEFAULT_SESSIONS_TAB,
} from "./constants.js";

export const appState = {
  db: null,
  sessionStats: new Map(),
  builtInCoverImageOptions: [],
  builtInCoverImageOptionsLoading: false,
  pendingArtTarget: null,
  cropSession: null,
  activeScreenId: DEFAULT_SCREEN_ID,
  activeSessionsTab: DEFAULT_SESSIONS_TAB,
  activeCharacterTab: DEFAULT_CHARACTER_TAB,
  homeLibraryStatusFilter: "all",
  homeLibraryExpanded: false,
  latestIdleJourney: null,
  editingCharacterName: false,
  showCharacterSkillModal: false,
  characterSkillModalScrollTop: 0,
  isJourneyEventResolving: false,
  journeyOutcomeNextEventId: "",
  journeyEventDockExpanded: false,
  journeyEventDockEventId: "",
  journeyEventDockDismissedIds: [],
  themePreference: "system",
  locale: "en",
  focusedGoalsEnabled: DEFAULT_FOCUSED_GOALS_ENABLED,
  onboarding: {
    active: false,
    lockBodyScroll: false,
    stepId: "",
    mode: "idle",
  },
  renderApp: async () => {},
};
